### ISSUE TITLE
Typo: BackGroundColour

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx-Profile-EPIP#16]
https://github.com/NeTEx-CEN/NeTEx-Profile-EPIP/blob/master/_content_NeTEx_EPIP.xsd#L2396

**Comment by TuThoThai** [comment]
@skinkie, just saw your issue. Would you like me to do the changes?

**Comment by skinkie** [comment]
Sure :-)

**Comment by TuThoThai** [comment]
@EliotTerrier is on it! :D
