### ISSUE TITLE
Suitabilities should be removed

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx-Profile-EPIP#2]
https://github.com/NeTEx-CEN/NeTEx/issues/271

**Comment by ue71603** [comment]
EPIP allows for suitabilities. EPIAP does not. Therefore in table 32 of EPIP suitabilites should be marked as not to be used.

christophe: agreed on my side

**Comment by Aurige** [comment]
doc updated (just a single sentence in fact)
